### ISSUE TITLE
Possible issue with <input type="email">

### ISSUE THREAD

**Issue by Reached** [riverside/form-serialize#1]
Hi there :)

Great library 👍 

However I think there might be an issue when using `<input type="email">`.

It does not add the value to the serialize object it seems, if I change it to <input type="text"> it works as expected.

Am I missing something here?

**Comment by riverside** [comment]
Hi @Reached,

This is because the script is a bit outdated. I just added HTML5 support. Now works fine.

Thank you for the feedback!

**Comment by Reached** [comment]
No problem, and thanks to you again for writing the lib @riverside ! :)
